<?php

namespace CKHan\LASAdapter\Grid\Exporters;

use Encore\Admin\Grid\Exporters\CsvExporter as AdminCsvExporter;
use Encore\Admin\Grid\Column;

class CsvExporter extends AdminCsvExporter
{
    /**
     * Get download response headers.
     *
     * @return array
     */
    protected function getHeaders()
    {
        $headers = parent::getHeaders(); // TODO: Change the autogenerated stub
        if(defined('SWOOLE_VERSION'))
            unset($headers['Content-Encoding']);
        return $headers;
    }

    /**
     * @return mixed|void
     */
    public function export()
    {
        if ($this->callback) {
            call_user_func($this->callback, $this);
        }

        $response = function () {
            $handle = fopen('php://output', 'w');
            $titles = [];
            fwrite($handle, chr(0xEF).chr(0xBB).chr(0xBF)); //导出的CSV文件是无BOM编码UTF-8，而我们通常使用UTF-8编码格式都是有BOM的。所以添加BOM于CSV中
            $this->chunk(function ($collection) use ($handle, &$titles) {
                Column::setOriginalGridModels($collection);

                $original = $current = $collection->toArray();

                $this->grid->getColumns()->map(function (Column $column) use (&$current) {
                    $current = $column->fill($current);
                    $this->grid->columnNames[] = $column->getName();
                });

                // Write title
                if (empty($titles)) {
                    fputcsv($handle, $titles = $this->getVisiableTitles());
                }

                // Write rows
                foreach ($current as $index => $record) {
                    fputcsv($handle, $this->getVisiableFields($record, $original[$index]));
                }
            });
            fclose($handle);
        };
        return response()->stream($response, 200, $this->getHeaders());
    }
}
